manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/LucaCiucci
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: eclair_ci
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - percepio
          - picolibc
          - segger
          - hal_nxp
  self:
    path: temp_alert
