name: "ECLAIR analysis (zephyr-workbench action)"
on:
  push:
    branches:
      - 'zephyr-workbench-demo'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ANALYSIS_KIND: zephyr_workbench_eclair_config
  ENABLE_ECLAIR_BOT: true

jobs:
  Zephyr-Workbench-Guidelines:
    strategy:
      matrix:
        board: ["stm32f746g_disco"]
    runs-on: saas.eclairit.com
    container:
      image: bugseng/github-runner:latest
      options: --pull always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Prepare
        run: |
          set -eu
          ./setup.sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and analyze with ECLAIR
        id: run-analyze
        uses: BUGSENG/zephyr-workbench-eclair-tools/cli@main
        with:
          project-dir: '.'
          board: 'stm32f746g_disco'
          config: 'Application Only'
          venv-path: '../.venv'

      - name: ECLAIR analysis log
        if: always()
        run: cat ${{ steps.run-analyze.outputs.sca-dir }}/DIAGNOSTIC.txt

      - name: Artifact name
        id: artifact_name
        if: always()
        run: |
          set -eu
          BOARD_NAME=${{ matrix.board }}
          echo "ARTIFACT_NAME=ECLAIR_out_zephyr_workbench_cfg_$(echo "${BOARD_NAME}" | tr '/' '_')" >> $GITHUB_ENV

      - name: Upload ECLAIR database
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eclair-out
          path: ${{ steps.run-analyze.outputs.sca-dir }}

      - name: Publish ECLAIR results
        if: always()
        env:
          WTOKEN: ${{secrets.WTOKEN}}
          VARIANT: ${{ matrix.board }}
        run: ECLAIR/action_push.sh "${WTOKEN}" ${{ steps.run-analyze.outputs.sca-dir }}
