name: "ECLAIR coding guidelines compliance"
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'tests/**'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ANALYSIS_KIND: coding_guidelines
  ENABLE_ECLAIR_BOT: true
jobs:
  Coding-Guidelines:
    strategy:
      matrix:
        board: ["frdm_mcxn947/mcxn947/cpu0", "stm32f746g_disco"]
    runs-on: saas.eclairit.com
    container:
      image: bugseng/github-runner:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Prepare
        run: |
          set -eu
          ./setup.sh
      - name: Build and analyze with ECLAIR
        id: build_and_analyze_with_eclair
        env:
          VARIANT: ${{ matrix.board }}
        run: |
          set -eu
          ./ECLAIR/analyze.sh ${{ matrix.board }}
      - name: Check regressions
        id: regressions
        env:
          cleanRegressionsLog: build/sca/eclair/clean_regressions.log
        run: |
          set -eu
          ./ECLAIR/action_check_clean_regressions.sh build/sca/eclair
      - name: ECLAIR analysis log
        if: always()
        run: cat build/sca/eclair/DIAGNOSTIC.txt
      - name: Artifact name
        id: artifact_name
        if: always()
        run: |
          set -eu
          BOARD_NAME=${{ matrix.board }}
          echo "ARTIFACT_NAME=ECLAIR_out_$(echo "${BOARD_NAME}" | tr '/' '_')" >> $GITHUB_ENV
      - name: Publish ECLAIR results
        if: always()
        env:
          WTOKEN: ${{secrets.WTOKEN}}
          VARIANT: ${{ matrix.board }}
        run: ECLAIR/action_push.sh "${WTOKEN}" build/sca/eclair
