name: "ECLAIR coverage and requirements"
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'tests/**'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ENABLE_ECLAIR_BOT: true
jobs:
  Coverage-and-Requirements:
    runs-on: saas.eclairit.com
    container:
      image: bugseng/github-runner:latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Prepare
        run: |
          set -eu
          ./setup.sh
      - name: Validate temp_alert.sdoc with StrictDoc
        run: |
          set -eu
          . ../.venv/bin/activate
          strictdoc export --formats=html temp_alert.sdoc --output-dir strictdoc_output
      - name: Configure GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - name: Upload StrictDoc HTML artifact for GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: strictdoc_output/html
      - name: Deploy artifact
        id: strictdoc-deploy
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
      - name: Upload StrictDoc HTML
        uses: actions/upload-artifact@v4
        with:
          name: strictdoc-html
          path: strictdoc_output/
      - name: Post requirements summary
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const deployUrl = '${{ steps.strictdoc-deploy.outputs.page_url }}';
            const sha = '${{ github.sha }}';
            const fs = require('fs');

            const body = `<img src="https://saas.eclairit.com:3787/rsrc/eclair.svg" width="100" /> Requirements Documentation

            [Browse requirements document](${deployUrl})`;

            // Post commit comment
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: body
            });

            // Add to workflow run summary
            fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, body + '\n');
      - name: Check temp_alert.sdoc
        run: |
          set -eu && \
          . ../.venv/bin/activate && \
          ./scripts/check_requirements.py temp_alert.sdoc
      - name: Build and analyze requirements coverage with ECLAIR
        run: |
          set -eu
          . ../.venv/bin/activate
          west analyze-requirements -t native_sim --config
      - name: Build and analyze coverage with ECLAIR
        run: |
          set -eu
          . ../.venv/bin/activate
          west analyze-coverage
      - name: ECLAIR analysis log
        if: always()
        run: cat ECLAIR/coverage_analysis_out/DIAGNOSTICS.txt
      - name: Artifact name
        id: artifact_name
        if: always()
        run: |
          set -eu
          echo "ARTIFACT_NAME=ECLAIR_out_coverage" >> $GITHUB_ENV
      - name: Publish ECLAIR requirements traceability results
        env:
          WTOKEN: ${{secrets.WTOKEN}}
          VARIANT: ${{ matrix.board }}
          ANALYSIS_KIND: requirements_coverage
        run: ECLAIR/action_push.sh "${WTOKEN}" ECLAIR/requirements_analysis_out
      - name: Publish ECLAIR code coverage results
        env:
          WTOKEN: ${{secrets.WTOKEN}}
          VARIANT: ${{ matrix.board }}
          ANALYSIS_KIND: test_coverage
        run: ECLAIR/action_push.sh "${WTOKEN}" ECLAIR/coverage_analysis_out

