name: "temp_alert tests"
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'ECLAIR/**'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Test:
    runs-on: saas.eclairit.com
    container:
      image: ubuntu:24.04
    steps:
      - name: Install basic deps
        run: |
          apt update
          apt install -y git
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Prepare
        run: |
          set -eu
          ./setup.sh
      - name: Twister tests
        run: |
          set -eu
          . ../.venv/bin/activate
          west twister -T tests --coverage --coverage-basedir . --platform native_sim
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_artifacts
          path: |
            twister-out/testplan.json
            twister-out/twister.log
            twister-out/twister.json
            twister-out/twister_report.xml
            twister-out/twister_suite_report.xml
            twister-out/twister.xml
